# Generated by Django 5.1 on 2025-03-05 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeVerification',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('current_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('new_email', models.EmailField(max_length=254)),
                ('code_verification', models.CharField(max_length=4)),
            ],
        ),
    ]
