# Generated by Django 5.1 on 2025-03-07 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeverification', '0002_alter_codeverification_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codeverification',
            old_name='id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='codeverification',
            name='current_email',
        ),
    ]
