# Generated by Django 5.1 on 2024-08-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdata',
            name='qr',
            field=models.FileField(blank=True, upload_to='qr/'),
        ),
        migrations.AddField(
            model_name='useramount',
            name='receipt',
            field=models.FileField(blank=True, upload_to='receipt/'),
        ),
    ]
