# Generated by Django 5.1 on 2024-08-22 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_userprofileimage_alter_bankdata_qr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdata',
            name='qr',
            field=models.ImageField(blank=True, upload_to='qr/'),
        ),
        migrations.AlterField(
            model_name='useramount',
            name='receipt',
            field=models.FileField(blank=True, upload_to='receipt/'),
        ),
        migrations.AlterField(
            model_name='userprofileimage',
            name='image',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
