# Generated by Django 5.1 on 2024-09-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_userprofileimage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileimage',
            name='image',
            field=models.ImageField(blank=True, default='defaultUserProfile', null=True, upload_to='image/'),
        ),
    ]
