# Generated by Django 5.1 on 2024-09-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_userprofileimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileimage',
            name='image',
            field=models.ImageField(blank=True, default='image/defaultUserProfile.png', null=True, upload_to='image/'),
        ),
    ]
